### ISSUE TITLE
Make channel checks optional and consistent

### ISSUE THREAD

**Issue by FungiOfDeath** [TheSorton/arisu#3]
# Current Behavior

If the user attempts to use (assuming prefix is `/`) `/pape`, it checks that the user is in the channel specified in the config as `botChan`.

If the user attempts to use `/cat`, no such check is made.

# Desired Behavior

Whoever is running the bot may choose which commands are checked. As well, all commands may include a check, and have an option in the config.

## Suggested Configurations

I suggest one of the following configuration schemes:

### Method 1

```json
{
  ...moreconfigs,
  "command": {
    "channel": "numbergoeshere",
    "check-channel": true
  },
  "next-command": {
    "channel": null,
    "check-channel": false
  }
}
```

### Method 2

```json
{
  ...moreconfigs,
  "commands": [
    {
      "name": "<command>",
      "channel": "number",
      "check-channel": true
    },
    {
      "name": "<next-command>",
      "channel": null,
      "check-channel": false
    }
  ]
}
```

### Method 3

```json
{
  ...moreconfigs,
  "commands": [
    {
      "name": "<command>",
      "channel": "number",
    },
    {
      "name": "<next-command>",
      "channel": false,
    }
  ]
}
```

# Misc

All of the above configurations have an additional advantage: they establish a scheme that may be used in the future for per-command configuration.

**Method 2** is better than **Method 1** IMO, as it groups all per-command configurations together into a single part of the json (namely, the `commands` array).

However, **Method 2** has the issue that the configuration may specify to check channels, but may also give an channel name of `null`. This inconsistency should be avoided if possible. Hence, I recommend using **Method 3**. If the configuration uses `null` or `false` as the value of `channel`, it assumes checks are disabled.

**Comment by TheSorton** [comment]
pape command is preferred in a bot channel since its embed. cat doesn't do this. really, consistency isn't the main focus since the checks are based on what i'd prefer.
